[package]
name = "essential-builder"
description = "A block builder library implementation for the Essential protocol"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
essential-node = { workspace = true }
