[workspace]
members = [
    "crates/*"
]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Essential Contributions <contact@essentialcontributions.com>"]
homepage = "https://essential.builders/"
repository = "https://github.com/essential-contributions/essential-builder"

[workspace.dependencies]
essential-builder = { path = "crates/builder", version = "0.1.0" }
essential-node = { git = "ssh://git@github.com/essential-contributions/essential-node.git" }

