[package]
name = "essential-builder-api"
description = "API implementation for the Essential builder"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
essential-builder = { workspace = true }
